"""Explicit PostgreSQL esquema 6 → stable HTTP/domain field mapping. SQL itself uses Spanish names."""

TABLE_NAMES = {
    "organizations": "empresas",
    "users": "usuarios",
    "assay_catalog": "catalogo_ensayos",
    "requests": "solicitudes",
    "samples": "muestras",
    "sample_assays": "ensayos_muestra",
    "reports": "informes",
    "activity": "actividad",
    "sessions": "sesiones",
    "rate_limits": "limites_intentos",
    "schema_migrations": "migraciones_esquema",
}
FIELD_NAMES = {
    "name": "nombre",
    "tax_id": "identificacion_tributaria",
    "active": "activo",
    "is_internal": "es_interna",
    "phone": "num_telefono",
    "organization_id": "empresa_id",
    "email": "correo",
    "password_hash": "hash_contrasena",
    "created_at": "creado_en",
    "code": "codigo",
    "user_id": "usuario_id",
    "project_id": "proyecto_id",
    "method": "metodo",
    "category": "categoria",
    "created_by": "creado_por",
    "title": "titulo",
    "status": "estado_solicitud",
    "notes": "observaciones",
    "target_date": "fecha_objetivo",
    "district": "distrito",
    "province": "provincia",
    "department": "departamento",
    "easting": "coordenada_este",
    "northing": "coordenada_norte",
    "updated_at": "actualizado_en",
    "request_id": "solicitud_id",
    "client_code": "codigo_cliente",
    "borehole": "calicata_sondaje",
    "depth_from": "profundidad_inicial",
    "depth_to": "profundidad_final",
    "quantity": "cantidad",
    "weight": "peso",
    "received_at": "recibido_en",
    "received_by": "recibido_por",
    "transport": "transporte",
    "received_quantity": "cantidad_recibida",
    "received_weight": "peso_recibido",
    "condition": "condicion",
    "reception_notes": "observaciones_recepcion",
    "sample_id": "muestra_id",
    "assay_id": "ensayo_id",
    "review_status": "estado_revision",
    "technician_id": "tecnico_id",
    "state": "estado_ensayo",
    "planned_start": "inicio_previsto",
    "planned_end": "fin_previsto",
    "started_at": "iniciado_en",
    "completed_at": "completado_en",
    "storage_key": "clave_archivo",
    "bytes": "tamano_bytes",
    "uploaded_by": "subido_por",
    "actor_id": "autor_id",
    "kind": "tipo",
    "message": "mensaje",
    "detail": "detalle",
    "internal": "interno",
    "token_hash": "hash_token",
    "last_seen": "ultimo_acceso",
    "expires_at": "vence_en",
    "key": "clave_limite",
    "count": "numero_intentos",
    "window_start": "inicio_ventana",
    "applied_at": "aplicado_en",
}
HTTP_FIELDS = {value: key for key, value in FIELD_NAMES.items()}


def domain_row(row):
    result = {HTTP_FIELDS.get(key, key): value for key, value in row.items()}
    if "review_status" in result:
        result["approved"] = result["review_status"] == "APPROVED"
    return result
